<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 1 One-Group Inference Tests | Statistics Handbook</title>
  <meta name="description" content="Notes cobbled together from books, online classes, etc. to be used as quick reference for common work projects." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 1 One-Group Inference Tests | Statistics Handbook" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Notes cobbled together from books, online classes, etc. to be used as quick reference for common work projects." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1 One-Group Inference Tests | Statistics Handbook" />
  
  <meta name="twitter:description" content="Notes cobbled together from books, online classes, etc. to be used as quick reference for common work projects." />
  

<meta name="author" content="Michael Foley" />


<meta name="date" content="2021-01-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="two-group-comparison-tests.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>
<link href="libs/table1-1.0/table1_defaults.css" rel="stylesheet" />
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/tabwid-1.0.0/tabwid.css" rel="stylesheet" />
<script src="libs/tabwid-1.0.0/tabwid.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="1" data-path="one-group-inference-tests.html"><a href="one-group-inference-tests.html"><i class="fa fa-check"></i><b>1</b> One-Group Inference Tests</a><ul>
<li class="chapter" data-level="1.1" data-path="one-group-inference-tests.html"><a href="one-group-inference-tests.html#one-group-inference-with-numeric-variable"><i class="fa fa-check"></i><b>1.1</b> One-Group Inference with Numeric Variable</a><ul>
<li class="chapter" data-level="1.1.1" data-path="one-group-inference-tests.html"><a href="one-group-inference-tests.html#one-sample-z-test-for-numeric-var"><i class="fa fa-check"></i><b>1.1.1</b> One Sample z Test for Numeric Var</a></li>
<li class="chapter" data-level="1.1.2" data-path="one-group-inference-tests.html"><a href="one-group-inference-tests.html#one-sample-t-test-for-numeric-var"><i class="fa fa-check"></i><b>1.1.2</b> One sample t Test for Numeric Var</a></li>
<li class="chapter" data-level="1.1.3" data-path="one-group-inference-tests.html"><a href="one-group-inference-tests.html#wilcoxon-1-sample-median-test-for-numeric-var"><i class="fa fa-check"></i><b>1.1.3</b> Wilcoxon 1-Sample Median Test for Numeric Var</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="one-group-inference-tests.html"><a href="one-group-inference-tests.html#one-group-inference-with-categorical-variable"><i class="fa fa-check"></i><b>1.2</b> One-Group Inference with Categorical Variable</a><ul>
<li class="chapter" data-level="1.2.1" data-path="one-group-inference-tests.html"><a href="one-group-inference-tests.html#sample-z-test-for-categorical-var"><i class="fa fa-check"></i><b>1.2.1</b> 1 Sample z Test for Categorical Var</a></li>
<li class="chapter" data-level="1.2.2" data-path="one-group-inference-tests.html"><a href="one-group-inference-tests.html#sample-t-test-for-categorical-var"><i class="fa fa-check"></i><b>1.2.2</b> 1 sample t Test for Categorical Var</a></li>
<li class="chapter" data-level="1.2.3" data-path="one-group-inference-tests.html"><a href="one-group-inference-tests.html#wilcoxon-1-sample-median-test-for-categorical-var"><i class="fa fa-check"></i><b>1.2.3</b> Wilcoxon 1-Sample Median Test for Categorical Var</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html"><i class="fa fa-check"></i><b>2</b> Two-Group Comparison Tests</a><ul>
<li class="chapter" data-level="2.1" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#two-group-comparison-tests-for-numeric-vars"><i class="fa fa-check"></i><b>2.1</b> Two-Group Comparison Tests for Numeric Vars</a><ul>
<li class="chapter" data-level="2.1.1" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#sample-independent-t-test-for-numeric-vars"><i class="fa fa-check"></i><b>2.1.1</b> 2 Sample Independent t Test for Numeric Vars</a></li>
<li class="chapter" data-level="2.1.2" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#sample-welchs-t-test-for-numeric-vars"><i class="fa fa-check"></i><b>2.1.2</b> 2 Sample Welch’s t Test for Numeric Vars</a></li>
<li class="chapter" data-level="2.1.3" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#paired-sample-t-test-for-numeric-vars"><i class="fa fa-check"></i><b>2.1.3</b> Paired Sample t Test for Numeric Vars</a></li>
<li class="chapter" data-level="2.1.4" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#mann-whitney-u-test-for-numeric-vars"><i class="fa fa-check"></i><b>2.1.4</b> Mann-Whitney U Test for Numeric Vars</a></li>
<li class="chapter" data-level="2.1.5" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#wilcoxon-paired-sample-test-for-numeric-vars"><i class="fa fa-check"></i><b>2.1.5</b> Wilcoxon Paired-Sample Test for Numeric Vars</a></li>
<li class="chapter" data-level="2.1.6" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#pearsons-correlation-for-numeric-vars"><i class="fa fa-check"></i><b>2.1.6</b> Pearson’s Correlation for Numeric Vars</a></li>
<li class="chapter" data-level="2.1.7" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#spearmans-ranked-correlation-for-numeric-vars"><i class="fa fa-check"></i><b>2.1.7</b> Spearman’s Ranked Correlation for Numeric Vars</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#two-group-comparison-tests-for-categorical-vars"><i class="fa fa-check"></i><b>2.2</b> Two-Group Comparison Tests for Categorical Vars</a><ul>
<li class="chapter" data-level="2.2.1" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#sample-independent-t-test-for-categorical-vars"><i class="fa fa-check"></i><b>2.2.1</b> 2 Sample Independent t Test for Categorical Vars</a></li>
<li class="chapter" data-level="2.2.2" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#sample-welchs-t-test-for-categorical-vars"><i class="fa fa-check"></i><b>2.2.2</b> 2 Sample Welch’s t Test for Categorical Vars</a></li>
<li class="chapter" data-level="2.2.3" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#paired-sample-t-test-for-categorical-vars"><i class="fa fa-check"></i><b>2.2.3</b> Paired Sample t Test for Categorical Vars</a></li>
<li class="chapter" data-level="2.2.4" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#mann-whitney-u-test-for-categorical-vars"><i class="fa fa-check"></i><b>2.2.4</b> Mann-Whitney U Test for Categorical Vars</a></li>
<li class="chapter" data-level="2.2.5" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#wilcoxon-paired-sample-test-for-categorical-vars"><i class="fa fa-check"></i><b>2.2.5</b> Wilcoxon Paired-Sample Test for Categorical Vars</a></li>
<li class="chapter" data-level="2.2.6" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#pearsons-correlation-for-categorical-vars"><i class="fa fa-check"></i><b>2.2.6</b> Pearson’s Correlation for Categorical Vars</a></li>
<li class="chapter" data-level="2.2.7" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#spearmans-ranked-correlation-for-categorical-vars"><i class="fa fa-check"></i><b>2.2.7</b> Spearman’s Ranked Correlation for Categorical Vars</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html"><i class="fa fa-check"></i><b>3</b> Multi-Group Comparison Tests</a><ul>
<li class="chapter" data-level="3.1" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#independent-t-test"><i class="fa fa-check"></i><b>3.1</b> Independent t-Test</a></li>
<li class="chapter" data-level="3.2" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#paired-t-test"><i class="fa fa-check"></i><b>3.2</b> Paired t-Test</a></li>
<li class="chapter" data-level="3.3" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#sign-est"><i class="fa fa-check"></i><b>3.3</b> Sign est</a></li>
<li class="chapter" data-level="3.4" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#wilcoxon-rank-sum-test"><i class="fa fa-check"></i><b>3.4</b> Wilcoxon Rank-Sum Test</a></li>
<li class="chapter" data-level="3.5" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>3.5</b> Wilcoxon Signed-Rank Test</a></li>
<li class="chapter" data-level="3.6" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#anova"><i class="fa fa-check"></i><b>3.6</b> ANOVA</a><ul>
<li class="chapter" data-level="3.6.1" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#one-way-anova"><i class="fa fa-check"></i><b>3.6.1</b> One-Way ANOVA</a></li>
<li class="chapter" data-level="3.6.2" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#welchs-anova-wgames-howell"><i class="fa fa-check"></i><b>3.6.2</b> Welch’s ANOVA w/Games-Howell</a></li>
<li class="chapter" data-level="3.6.3" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#manova"><i class="fa fa-check"></i><b>3.6.3</b> MANOVA</a></li>
<li class="chapter" data-level="3.6.4" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#multiple-variance-comparison-f-test"><i class="fa fa-check"></i><b>3.6.4</b> Multiple Variance Comparison F Test</a></li>
<li class="chapter" data-level="3.6.5" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#example-1"><i class="fa fa-check"></i><b>3.6.5</b> Example</a></li>
<li class="chapter" data-level="3.6.6" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#repeated-measures"><i class="fa fa-check"></i><b>3.6.6</b> Repeated Measures</a></li>
<li class="chapter" data-level="3.6.7" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#two-way"><i class="fa fa-check"></i><b>3.6.7</b> Two-Way</a></li>
<li class="chapter" data-level="3.6.8" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#randomized-blocks"><i class="fa fa-check"></i><b>3.6.8</b> Randomized Blocks</a></li>
<li class="chapter" data-level="3.6.9" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#ancova"><i class="fa fa-check"></i><b>3.6.9</b> ANCOVA</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#kruskalwallis-test"><i class="fa fa-check"></i><b>3.7</b> Kruskal–Wallis Test</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="applications.html"><a href="applications.html"><i class="fa fa-check"></i><b>4</b> Applications</a><ul>
<li class="chapter" data-level="4.1" data-path="applications.html"><a href="applications.html#example-one"><i class="fa fa-check"></i><b>4.1</b> Example one</a></li>
<li class="chapter" data-level="4.2" data-path="applications.html"><a href="applications.html#example-two"><i class="fa fa-check"></i><b>4.2</b> Example two</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>5</b> Final Words</a><ul>
<li class="chapter" data-level="5.1" data-path="final-words.html"><a href="final-words.html#pearson"><i class="fa fa-check"></i><b>5.1</b> Pearson</a></li>
<li class="chapter" data-level="5.2" data-path="final-words.html"><a href="final-words.html#chi-square"><i class="fa fa-check"></i><b>5.2</b> Chi-Square</a></li>
<li class="chapter" data-level="5.3" data-path="final-words.html"><a href="final-words.html#spearman"><i class="fa fa-check"></i><b>5.3</b> Spearman</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="final-words-1.html"><a href="final-words-1.html"><i class="fa fa-check"></i><b>6</b> Final Words</a><ul>
<li class="chapter" data-level="6.1" data-path="final-words-1.html"><a href="final-words-1.html#linear"><i class="fa fa-check"></i><b>6.1</b> Linear</a></li>
<li class="chapter" data-level="6.2" data-path="final-words-1.html"><a href="final-words-1.html#generalized-linear"><i class="fa fa-check"></i><b>6.2</b> Generalized Linear</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="Probablity.html"><a href="Probablity.html"><i class="fa fa-check"></i><b>7</b> Probability</a><ul>
<li class="chapter" data-level="7.1" data-path="Probablity.html"><a href="Probablity.html#bayesian-inference"><i class="fa fa-check"></i><b>7.1</b> Bayesian Inference</a></li>
<li class="chapter" data-level="7.2" data-path="Probablity.html"><a href="Probablity.html#stochastic-processes"><i class="fa fa-check"></i><b>7.2</b> Stochastic Processes</a><ul>
<li class="chapter" data-level="7.2.1" data-path="Probablity.html"><a href="Probablity.html#markov-chains"><i class="fa fa-check"></i><b>7.2.1</b> Markov Chains</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistics Handbook</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="one-group-inference-tests" class="section level1">
<h1><span class="header-section-number">Chapter 1</span> One-Group Inference Tests</h1>
<p><em>One-group</em> refers to a single population whose metric you are trying to measure. In the case of a quantitative metric, you are typically measuring its mean value. In the case of a count variable, you are typically measuring its proportion.</p>
<div id="one-group-inference-with-numeric-variable" class="section level2">
<h2><span class="header-section-number">1.1</span> One-Group Inference with Numeric Variable</h2>
<p>The tests in this section use the sample mean, <span class="math inline">\(\bar{x}\)</span>, as an estimate of the population mean, <span class="math inline">\(\mu\)</span>. The tests apply when the data is <em>independent</em>. Using the normal or student-t distribution, you can create a confidence interval around the estimate, or evaluate an hypothesized population mean, <span class="math inline">\(\mu_0\)</span>. Which test you use depends on what you know about the population distribution (normal vs non-normal) and its variance (known or unknown):</p>
<table>
<thead>
<tr class="header">
<th></th>
<th>Normal Distribution</th>
<th>Non-Normal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Known Variance</td>
<td><em>z</em>-test</td>
<td>Wilcoxon Median</td>
</tr>
<tr class="even">
<td>Unknown Variance</td>
<td><em>t</em>-test</td>
<td>Wilcoxon Median</td>
</tr>
</tbody>
</table>
<div id="one-sample-z-test-for-numeric-var" class="section level3">
<h3><span class="header-section-number">1.1.1</span> One Sample z Test for Numeric Var</h3>
<p>The <em>z</em> test is also called the normal approximation <em>z</em> test. It only applies when the sampling distribution of the population mean is normally distributed with known variance, and there are no significant outliers. The sampling distribution is normally distributed when the underlying population is normally distributed, or when the sample size is large <span class="math inline">\((n &gt;= 30)\)</span>, as follows from the central limit theorem. The <em>t</em> test returns similar results, plus it is valid when the variance is unknown, and that is pretty much always. For that reason, you probably will never use this test.</p>
<p>Under the normal approximation method, the measured mean <span class="math inline">\(\bar{x}\)</span> approximates the population mean <span class="math inline">\(\mu\)</span>, and the sampling distribution has a normal distribution centered at <span class="math inline">\(\mu\)</span> with standard error <span class="math inline">\(se_\mu = \frac{\sigma}{\sqrt{n}}\)</span> where <span class="math inline">\(\sigma\)</span> is the standard deviation of the underlying population. Define a <span class="math inline">\((1 - \alpha)\%\)</span> confidence interval as <span class="math inline">\(\bar{x} \pm z_{(1 - \alpha) {/} 2} se_\mu\)</span>, or test <span class="math inline">\(H_0: \mu = \mu_0\)</span> with test statistic <span class="math inline">\(Z = \frac{\bar{x} - \mu_0}{se_\mu}\)</span>.</p>
<div id="example" class="section level4 unnumbered">
<h4>Example</h4>
<p>The <code>mtcars</code> data set is a sample of <em>n</em> = 32 cars. The mean fuel economy is <span class="math inline">\(\bar{x} \pm s\)</span> = 20.1 <span class="math inline">\(\pm\)</span> 6.0 mpg. The prior measured overall fuel economy for vehicles was <span class="math inline">\(\mu_0 \pm \sigma\)</span> = 18.0 <span class="math inline">\(\pm\)</span> 6.0 mpg. Has fuel economy improved?</p>
<p>The sample size is <span class="math inline">\(\ge\)</span> 30, so the sampling distribution of the population mean is normally distributed. The population variance is known, so use the <em>z</em> test.</p>
<p><span class="math inline">\(H_0: \mu = 16.0\)</span>, and <span class="math inline">\(H_a: \mu &gt; 16.0\)</span> - a right-tail test. The test statistic is <span class="math inline">\(Z = \frac{\bar{x} - \mu_0}{se_\mu}=\)</span> 1.97 where <span class="math inline">\(se_{\mu_0} = \frac{\mu_0}{\sqrt{n}} =\)</span> 1.06. <span class="math inline">\(P(z &gt; Z) =\)</span> 0.0244, so reject <span class="math inline">\(H_0\)</span> at the <span class="math inline">\(\alpha =\)</span> 0.05 level of significance.</p>
<p><img src="statistics_files/figure-html/unnamed-chunk-5-1.png" width="624" /></p>
<p>The 95% confidence interval for <span class="math inline">\(\mu\)</span> is <span class="math inline">\(\bar{x} \pm z_{(1 - \alpha){/}2} se_\mu\)</span> where <span class="math inline">\(z_{(1 - \alpha){/}2} =\)</span> 1.96. <span class="math inline">\(\mu =\)</span> 20.09 <span class="math inline">\(\pm\)</span> 2.08 (95% CI 18.01 to 22.17).</p>
<p><img src="statistics_files/figure-html/unnamed-chunk-7-1.png" width="624" /></p>
</div>
</div>
<div id="one-sample-t-test-for-numeric-var" class="section level3">
<h3><span class="header-section-number">1.1.2</span> One sample t Test for Numeric Var</h3>
<p>The one-sample <em>t</em> test applies when the sampling distribution of the population mean is normally distributed and there are no significant outliers. Unlike the <em>z</em> test, the population variance can be unknown. The sampling distribution is normally distributed when the underlying population is normally distributed, or when the sample size is large <span class="math inline">\((n &gt;= 30)\)</span>, as follows from the central limit theorem.</p>
<p>Under the <em>t</em> test method, the measured mean, <span class="math inline">\(\bar{x}\)</span>, approximates the population mean, <span class="math inline">\(\mu\)</span>. The sample standard deviation, <span class="math inline">\(s\)</span>, estimates the unknown population standard deviation, <span class="math inline">\(\sigma\)</span>. The resulting sampling distribution has a <em>t</em> distribution centered at <span class="math inline">\(\mu\)</span> with standard error <span class="math inline">\(se_\bar{x} = \frac{s}{\sqrt{n}}\)</span>. Define a <span class="math inline">\((1 - \alpha)\%\)</span> confidence interval as <span class="math inline">\(\bar{x} \pm t_{(1 - \alpha){/}2} se_\bar{x}\)</span> and/or test <span class="math inline">\(H_0: \mu = \mu_0\)</span> with test statistic <span class="math inline">\(T = \frac{\bar{x} - \mu_0}{se_\bar{x}}\)</span>.</p>
<p>Here is a case study. A researcher recruits a random sample of <em>n</em> = 40 people to participate in a study about depression intervention. The researcher measures the participants’ depression level prior to the study. The mean depression score (3.72 <span class="math inline">\(\pm\)</span> 0.74) was lower than the population ‘normal’ depression score of 4.0. The null hypothesis is that the sample is representative of the overall population. Should you reject <span class="math inline">\(H_0\)</span>?</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="one-group-inference-tests.html#cb1-1"></a>dep <span class="op">%&gt;%</span><span class="st"> </span>gtsummary<span class="op">::</span><span class="kw">tbl_summary</span>(<span class="dt">statistic =</span> <span class="kw">list</span>(<span class="kw">all_continuous</span>() <span class="op">~</span><span class="st"> &quot;{mean} ({sd})&quot;</span>))</span></code></pre></div>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#ipxztsvchb .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ipxztsvchb .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ipxztsvchb .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ipxztsvchb .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ipxztsvchb .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ipxztsvchb .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ipxztsvchb .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ipxztsvchb .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ipxztsvchb .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ipxztsvchb .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ipxztsvchb .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ipxztsvchb .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#ipxztsvchb .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ipxztsvchb .gt_from_md > :first-child {
  margin-top: 0;
}

#ipxztsvchb .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ipxztsvchb .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ipxztsvchb .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#ipxztsvchb .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ipxztsvchb .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#ipxztsvchb .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ipxztsvchb .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ipxztsvchb .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ipxztsvchb .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ipxztsvchb .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ipxztsvchb .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#ipxztsvchb .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ipxztsvchb .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#ipxztsvchb .gt_left {
  text-align: left;
}

#ipxztsvchb .gt_center {
  text-align: center;
}

#ipxztsvchb .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ipxztsvchb .gt_font_normal {
  font-weight: normal;
}

#ipxztsvchb .gt_font_bold {
  font-weight: bold;
}

#ipxztsvchb .gt_font_italic {
  font-style: italic;
}

#ipxztsvchb .gt_super {
  font-size: 65%;
}

#ipxztsvchb .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="ipxztsvchb" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>N = 40</strong><sup class="gt_footnote_marks">1</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr>
      <td class="gt_row gt_left">dep_score</td>
      <td class="gt_row gt_center">3.72 (0.74)</td>
    </tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="2">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          Statistics presented: Mean (SD)
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table></div>
<div id="conditions" class="section level4 unnumbered">
<h4>Conditions</h4>
<p>The one-sample <em>t</em> test applies when the variable is continuous and the observations are independent. Additionally, there are two conditions related to the data distribution. If either condition fails, try the suggested work-arounds or use the non-parametric <a href="one-group-inference-tests.html#wilcoxon-1-sample-median-test-for-numeric-var">Wilcoxon 1-Sample Median Test for Numeric Var</a> instead.</p>
<ol style="list-style-type: decimal">
<li><strong>Outliers</strong>. There should be no significant outliers. Outliers exert a large influence on the mean and standard deviation. Test with a box plot. If there are outliers, you might be able to drop them or transform the data.</li>
<li><strong>Normality</strong>. Values should be <em>nearly</em> normally distributed (“nearly” because the <em>t</em>-test is robust to the normality assumption). This condition is especially important with small sample sizes. Test with Q-Q plots or the Shapiro-Wilk test for normality. If the data is very non-normal, you might be able to transform the data.</li>
</ol>
<div id="outliers" class="section level5 unnumbered">
<h5>Outliers</h5>
<p>Assess outliers with a box plot. Box plot whiskers extend up to 1.5*IQR from the upper and lower hinges and outliers (beyond the whiskers) are are plotted individually. The boxplot shows no outliers.</p>
<p><img src="statistics_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>If the outliers might are data entry errors or measurement errors, fix them or discard them. If the outliers are genuine, you have a couple options before reverting to Wilcoxon.</p>
<ul>
<li>Transform the variable. Don’t do this unless the variable is also non-normal. Transformation also has the downside of making interpretation more difficult.</li>
<li>Leave it in if it doesn’t affect the conclusion (compared to taking it out).</li>
</ul>
</div>
<div id="normality" class="section level5 unnumbered">
<h5>Normality</h5>
<p>Assume the population is normally distributed if <em>n</em> <span class="math inline">\(\ge\)</span> 30. Otherwise, asses a Q-Q plot, skewness and kurtosis values, or a histogram. If you still don’t feel confident about normality, run a [Shapiro-Wilk Test].</p>
<p>The data set has <em>n</em> = 40 observations, so you can assume normality. Here is a QQ plot anyway. The QQ plot indicates normality.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="one-group-inference-tests.html#cb2-1"></a>dep <span class="op">%&gt;%</span></span>
<span id="cb2-2"><a href="one-group-inference-tests.html#cb2-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">sample =</span> dep_score)) <span class="op">+</span></span>
<span id="cb2-3"><a href="one-group-inference-tests.html#cb2-3"></a><span class="st">  </span><span class="kw">stat_qq</span>() <span class="op">+</span></span>
<span id="cb2-4"><a href="one-group-inference-tests.html#cb2-4"></a><span class="st">  </span><span class="kw">stat_qq_line</span>(<span class="dt">col =</span> <span class="st">&quot;goldenrod&quot;</span>) <span class="op">+</span></span>
<span id="cb2-5"><a href="one-group-inference-tests.html#cb2-5"></a><span class="st">  </span><span class="kw">theme_minimal</span>() <span class="op">+</span></span>
<span id="cb2-6"><a href="one-group-inference-tests.html#cb2-6"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Normal Q-Q Plot&quot;</span>)</span></code></pre></div>
<p><img src="statistics_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Here is the Shapiro-Wilk normality test. It fails to reject the null hypothesis of a normally distributed population.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="one-group-inference-tests.html#cb3-1"></a><span class="kw">shapiro.test</span>(dep<span class="op">$</span>dep_score)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  dep$dep_score
## W = 0.98446, p-value = 0.8474</code></pre>
<p>If the data is not normally distributed, you still have a couple options before reverting to Wilcoxon.</p>
<ul>
<li>Transform the dependent variable.</li>
<li>Carry on regardless - the one-sample <em>t</em>-test is fairly robust to deviations from normality.</li>
</ul>
</div>
</div>
<div id="results" class="section level4 unnumbered">
<h4>Results</h4>
<p>Conduct the <em>t</em>-test. To get a 95% CI around the <em>difference</em> (instead of around the estimate), run the test using the difference, <span class="math inline">\(\mu_0 - \bar{x}\)</span>, and leave <code>mu</code> at its default of 0.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="one-group-inference-tests.html#cb5-1"></a>(dep_95ci &lt;-<span class="st"> </span><span class="kw">t.test</span>(<span class="dt">x =</span> mu_<span class="dv">0</span> <span class="op">-</span><span class="st"> </span>dep<span class="op">$</span>dep_score, <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="dt">conf.level =</span> <span class="fl">.95</span>))</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  mu_0 - dep$dep_score
## t = 2.3811, df = 39, p-value = 0.02224
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  0.04176615 0.51323385
## sample estimates:
## mean of x 
##    0.2775</code></pre>
<p>The difference is statistically different from 0 at the <em>p</em> = .05 level. The effect size, called Cohen’s <em>d</em>, is defined as <span class="math inline">\(d = |M_D| / s\)</span>, where <span class="math inline">\(|M_D| = \bar{x} - \mu_0\)</span>, and <span class="math inline">\(s\)</span> is the sample standard deviation. <span class="math inline">\(d &lt;.2\)</span> is considered trivial, <span class="math inline">\(.2 \le d &lt; .5\)</span> small, and <span class="math inline">\(.5 \le d &lt; .8\)</span> large.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="one-group-inference-tests.html#cb7-1"></a>(d &lt;-<span class="st"> </span>rstatix<span class="op">::</span><span class="kw">cohens_d</span>(dep, dep_score <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">mu =</span> <span class="dv">4</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(effsize) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">abs</span>())</span></code></pre></div>
<pre><code>## Cohen&#39;s d 
## 0.3764788</code></pre>
<p>Cohen’s <em>d</em> is 0.38, a small effect.</p>
<p>Make a habit of constructing a plot, just to make sure your head is on straight.</p>
<p><img src="statistics_files/figure-html/unnamed-chunk-15-1.png" width="624" /></p>
<p>Now you are ready to report the results.</p>
<blockquote>
<p>A one-sample <em>t</em>-test was run to determine whether depression score in recruited subjects was different from normal, as defined as a depression score of 4.0. Depression scores were normally distributed, as assessed by Shapiro-Wilk’s test (<em>p</em> &gt; .05) and there were no outliers in the data, as assessed by inspection of a boxplot. Data are mean <span class="math inline">\(\pm\)</span> standard deviation, unless otherwise stated. Mean depression score (3.72 <span class="math inline">\(\pm\)</span> 0.74) was lower than the population “normal” depression score of 4.00, a statistically significant difference of 0.28 (95% CI, 0.04 to 0.51), t(39) = 2.38, <em>p</em> = 0.022, <em>d</em> = 0.38.</p>
</blockquote>
</div>
<div id="appendix-deciding-sample-size" class="section level4 unnumbered">
<h4>Appendix: Deciding Sample Size</h4>
<p>Determine the sample size required for a maximum error <span class="math inline">\(\epsilon\)</span> in the estimate by solving the confidence interval equation, <span class="math inline">\(\bar{x} \pm t_{(1 - \alpha){/}2} \frac{s}{\sqrt{n}}\)</span> for <span class="math inline">\(n=\frac{{t_{\alpha/2,n-1}^2se^2}}{{\epsilon^2}}\)</span> . Unfortunately, <span class="math inline">\(t_{\alpha/2,n-1}^2\)</span> is dependent on <span class="math inline">\(n\)</span>, so replace it with <span class="math inline">\(z_{\alpha/2}^2\)</span>. What about <span class="math inline">\(s^2\)</span>? Estimate it from the literature, a pilot study, or using the empirical rule that 95% of the range falls within two standard deviations, <span class="math inline">\(s=range / 4\)</span>.</p>
<p>For example, if the maximum tolerable error is* <span class="math inline">\(\epsilon\)</span> = 3, and <span class="math inline">\(s\)</span> is approximately 10, what sample size produces an <span class="math inline">\(\alpha\)</span> =0.05 confidence level?</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="one-group-inference-tests.html#cb9-1"></a><span class="kw">ceiling</span>(<span class="kw">qnorm</span>(.<span class="dv">975</span>)<span class="op">^</span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="dv">10</span><span class="op">^</span><span class="dv">2</span> <span class="op">/</span><span class="st"> </span><span class="dv">3</span><span class="op">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 43</code></pre>
</div>
</div>
<div id="wilcoxon-1-sample-median-test-for-numeric-var" class="section level3">
<h3><span class="header-section-number">1.1.3</span> Wilcoxon 1-Sample Median Test for Numeric Var</h3>
<p>The Wilcoxon one-sample median test (aka Wilcoxon signed rank test) is a non-parametric alternative to the <em>t</em>-test for cases when the the sampling distribution of the population mean is <em>not</em> normally distributed, but is at least symmetric.</p>
<p>Under the Wilcoxon test, the measured median, <span class="math inline">\(\eta_x\)</span>, approximates the population median, <span class="math inline">\(\eta\)</span>. The method calculates the difference between each value and the hypothesized median, <span class="math inline">\(\eta_0\)</span>, ranks the difference magnitudes, then sums the ranks for the negative and the positive differences, <span class="math inline">\(W+\)</span> and <span class="math inline">\(W-\)</span>. The test compares the smaller of the two sums to a table of critical values.</p>
<p>Here is a case study. A store claims their checkout wait times are <span class="math inline">\(\le\)</span> 4 minutes. You challenge the claim by sampling 6 checkout experiences. The mean wait time was 4.6, but the data may violate normality.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="one-group-inference-tests.html#cb11-1"></a><span class="kw">data.frame</span>(<span class="dt">wait =</span> wait) <span class="op">%&gt;%</span></span>
<span id="cb11-2"><a href="one-group-inference-tests.html#cb11-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">sample =</span> wait)) <span class="op">+</span></span>
<span id="cb11-3"><a href="one-group-inference-tests.html#cb11-3"></a><span class="st">  </span><span class="kw">stat_qq</span>() <span class="op">+</span></span>
<span id="cb11-4"><a href="one-group-inference-tests.html#cb11-4"></a><span class="st">  </span><span class="kw">stat_qq_line</span>(<span class="dt">col =</span> <span class="st">&quot;goldenrod&quot;</span>) <span class="op">+</span></span>
<span id="cb11-5"><a href="one-group-inference-tests.html#cb11-5"></a><span class="st">  </span><span class="kw">theme_minimal</span>() <span class="op">+</span></span>
<span id="cb11-6"><a href="one-group-inference-tests.html#cb11-6"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Normal Q-Q Plot&quot;</span>)</span></code></pre></div>
<p><img src="statistics_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Shapiro-Wilk rejects the null hypothesis of a normally distributed population.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="one-group-inference-tests.html#cb12-1"></a><span class="kw">shapiro.test</span>(wait)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  wait
## W = 0.75105, p-value = 0.0204</code></pre>
<p>Use the Wilcoxon test instead.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="one-group-inference-tests.html#cb14-1"></a>(wt &lt;-<span class="st"> </span><span class="kw">wilcox.test</span>(wait, <span class="dt">mu =</span> <span class="dv">4</span>, <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>))</span></code></pre></div>
<pre><code>## Warning in wilcox.test.default(wait, mu = 4, alternative = &quot;greater&quot;): cannot
## compute exact p-value with ties</code></pre>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  wait
## V = 14.5, p-value = 0.2309
## alternative hypothesis: true location is greater than 4</code></pre>
<blockquote>
<p>A Wilcoxon Signed-Ranks Test indicated that wait times were <em>not</em> statistically significantly higher than the 4-minute claim, <em>z</em> = 14.5, <em>p</em> = 0.231.</p>
</blockquote>
</div>
</div>
<div id="one-group-inference-with-categorical-variable" class="section level2">
<h2><span class="header-section-number">1.2</span> One-Group Inference with Categorical Variable</h2>
<div id="sample-z-test-for-categorical-var" class="section level3">
<h3><span class="header-section-number">1.2.1</span> 1 Sample z Test for Categorical Var</h3>
<p>This test applies when you know the population variance.</p>
</div>
<div id="sample-t-test-for-categorical-var" class="section level3">
<h3><span class="header-section-number">1.2.2</span> 1 sample t Test for Categorical Var</h3>
<p>This test applies when you do not know the population variance.</p>
</div>
<div id="wilcoxon-1-sample-median-test-for-categorical-var" class="section level3">
<h3><span class="header-section-number">1.2.3</span> Wilcoxon 1-Sample Median Test for Categorical Var</h3>
<p>This test applies when the variable is not normally distributed.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="two-group-comparison-tests.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["statistics.pdf", "statistics.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
