<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Two-Group Comparison Tests | Statistics Handbook</title>
  <meta name="description" content="Notes cobbled together from books, online classes, etc. to be used as quick reference for common work projects." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Two-Group Comparison Tests | Statistics Handbook" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Notes cobbled together from books, online classes, etc. to be used as quick reference for common work projects." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Two-Group Comparison Tests | Statistics Handbook" />
  
  <meta name="twitter:description" content="Notes cobbled together from books, online classes, etc. to be used as quick reference for common work projects." />
  

<meta name="author" content="Michael Foley" />


<meta name="date" content="2021-02-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="one-sample-inference-tests.html"/>
<link rel="next" href="multi-group-comparison-tests.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="1" data-path="one-sample-inference-tests.html"><a href="one-sample-inference-tests.html"><i class="fa fa-check"></i><b>1</b> One-Sample Inference Tests</a><ul>
<li class="chapter" data-level="1.1" data-path="one-sample-inference-tests.html"><a href="one-sample-inference-tests.html#one-sample-mean-z-test"><i class="fa fa-check"></i><b>1.1</b> One-Sample Mean z Test</a></li>
<li class="chapter" data-level="1.2" data-path="one-sample-inference-tests.html"><a href="one-sample-inference-tests.html#one-sample-mean-t-test"><i class="fa fa-check"></i><b>1.2</b> One-Sample Mean t Test</a></li>
<li class="chapter" data-level="1.3" data-path="one-sample-inference-tests.html"><a href="one-sample-inference-tests.html#one-sample-median-wilcoxon-test"><i class="fa fa-check"></i><b>1.3</b> One-Sample Median Wilcoxon Test</a></li>
<li class="chapter" data-level="1.4" data-path="one-sample-inference-tests.html"><a href="one-sample-inference-tests.html#chi-squared-goodness-of-fit-test"><i class="fa fa-check"></i><b>1.4</b> Chi-Squared Goodness-of-Fit Test</a></li>
<li class="chapter" data-level="1.5" data-path="one-sample-inference-tests.html"><a href="one-sample-inference-tests.html#g-test"><i class="fa fa-check"></i><b>1.5</b> G-Test</a></li>
<li class="chapter" data-level="1.6" data-path="one-sample-inference-tests.html"><a href="one-sample-inference-tests.html#one-sample-poisson-test"><i class="fa fa-check"></i><b>1.6</b> One-Sample Poisson Test</a></li>
<li class="chapter" data-level="1.7" data-path="one-sample-inference-tests.html"><a href="one-sample-inference-tests.html#one-sample-binomial-test"><i class="fa fa-check"></i><b>1.7</b> One-Sample Binomial Test</a></li>
<li class="chapter" data-level="1.8" data-path="one-sample-inference-tests.html"><a href="one-sample-inference-tests.html#one-sample-proportion-z-test"><i class="fa fa-check"></i><b>1.8</b> One-Sample Proportion z Test</a></li>
<li class="chapter" data-level="1.9" data-path="one-sample-inference-tests.html"><a href="one-sample-inference-tests.html#sample-t-test-for-categorical-var"><i class="fa fa-check"></i><b>1.9</b> 1 sample t Test for Categorical Var</a></li>
<li class="chapter" data-level="1.10" data-path="one-sample-inference-tests.html"><a href="one-sample-inference-tests.html#wilcoxon-1-sample-median-test-for-categorical-var"><i class="fa fa-check"></i><b>1.10</b> Wilcoxon 1-Sample Median Test for Categorical Var</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html"><i class="fa fa-check"></i><b>2</b> Two-Group Comparison Tests</a><ul>
<li class="chapter" data-level="2.1" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#independent-samples-t-test"><i class="fa fa-check"></i><b>2.1</b> Independent Samples t Test</a></li>
<li class="chapter" data-level="2.2" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#paired-samples-t-test"><i class="fa fa-check"></i><b>2.2</b> Paired Samples t Test</a></li>
<li class="chapter" data-level="2.3" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#mann-whitney-u-test-for-numeric-vars"><i class="fa fa-check"></i><b>2.3</b> Mann-Whitney U Test for Numeric Vars</a></li>
<li class="chapter" data-level="2.4" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#wilcoxon-paired-sample-test-for-numeric-vars"><i class="fa fa-check"></i><b>2.4</b> Wilcoxon Paired-Sample Test for Numeric Vars</a></li>
<li class="chapter" data-level="2.5" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#pearsons-correlation-for-numeric-vars"><i class="fa fa-check"></i><b>2.5</b> Pearson’s Correlation for Numeric Vars</a></li>
<li class="chapter" data-level="2.6" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#spearmans-ranked-correlation-for-numeric-vars"><i class="fa fa-check"></i><b>2.6</b> Spearman’s Ranked Correlation for Numeric Vars</a></li>
<li class="chapter" data-level="2.7" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#sample-independent-t-test-for-categorical-vars"><i class="fa fa-check"></i><b>2.7</b> 2 Sample Independent t Test for Categorical Vars</a></li>
<li class="chapter" data-level="2.8" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#sample-welchs-t-test-for-categorical-vars"><i class="fa fa-check"></i><b>2.8</b> 2 Sample Welch’s t Test for Categorical Vars</a></li>
<li class="chapter" data-level="2.9" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#paired-sample-t-test-for-categorical-vars"><i class="fa fa-check"></i><b>2.9</b> Paired Sample t Test for Categorical Vars</a></li>
<li class="chapter" data-level="2.10" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#mann-whitney-u-test-for-categorical-vars"><i class="fa fa-check"></i><b>2.10</b> Mann-Whitney U Test for Categorical Vars</a></li>
<li class="chapter" data-level="2.11" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#wilcoxon-paired-sample-test-for-categorical-vars"><i class="fa fa-check"></i><b>2.11</b> Wilcoxon Paired-Sample Test for Categorical Vars</a></li>
<li class="chapter" data-level="2.12" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#pearsons-correlation-for-categorical-vars"><i class="fa fa-check"></i><b>2.12</b> Pearson’s Correlation for Categorical Vars</a></li>
<li class="chapter" data-level="2.13" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#spearmans-ranked-correlation-for-categorical-vars"><i class="fa fa-check"></i><b>2.13</b> Spearman’s Ranked Correlation for Categorical Vars</a></li>
<li class="chapter" data-level="2.14" data-path="two-group-comparison-tests.html"><a href="two-group-comparison-tests.html#fishers-exact-test"><i class="fa fa-check"></i><b>2.14</b> Fisher’s Exact Test</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html"><i class="fa fa-check"></i><b>3</b> Multi-Group Comparison Tests</a><ul>
<li class="chapter" data-level="3.1" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#independent-t-test"><i class="fa fa-check"></i><b>3.1</b> Independent t-Test</a></li>
<li class="chapter" data-level="3.2" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#paired-t-test"><i class="fa fa-check"></i><b>3.2</b> Paired t-Test</a></li>
<li class="chapter" data-level="3.3" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#sign-est"><i class="fa fa-check"></i><b>3.3</b> Sign est</a></li>
<li class="chapter" data-level="3.4" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#wilcoxon-rank-sum-test"><i class="fa fa-check"></i><b>3.4</b> Wilcoxon Rank-Sum Test</a></li>
<li class="chapter" data-level="3.5" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>3.5</b> Wilcoxon Signed-Rank Test</a></li>
<li class="chapter" data-level="3.6" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#anova"><i class="fa fa-check"></i><b>3.6</b> ANOVA</a><ul>
<li class="chapter" data-level="3.6.1" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#one-way-anova"><i class="fa fa-check"></i><b>3.6.1</b> One-Way ANOVA</a></li>
<li class="chapter" data-level="3.6.2" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#welchs-anova-wgames-howell"><i class="fa fa-check"></i><b>3.6.2</b> Welch’s ANOVA w/Games-Howell</a></li>
<li class="chapter" data-level="3.6.3" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#manova"><i class="fa fa-check"></i><b>3.6.3</b> MANOVA</a></li>
<li class="chapter" data-level="3.6.4" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#multiple-variance-comparison-f-test"><i class="fa fa-check"></i><b>3.6.4</b> Multiple Variance Comparison F Test</a></li>
<li class="chapter" data-level="3.6.5" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#example-7"><i class="fa fa-check"></i><b>3.6.5</b> Example</a></li>
<li class="chapter" data-level="3.6.6" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#repeated-measures"><i class="fa fa-check"></i><b>3.6.6</b> Repeated Measures</a></li>
<li class="chapter" data-level="3.6.7" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#two-way"><i class="fa fa-check"></i><b>3.6.7</b> Two-Way</a></li>
<li class="chapter" data-level="3.6.8" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#randomized-blocks"><i class="fa fa-check"></i><b>3.6.8</b> Randomized Blocks</a></li>
<li class="chapter" data-level="3.6.9" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#ancova"><i class="fa fa-check"></i><b>3.6.9</b> ANCOVA</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#kruskalwallis-test"><i class="fa fa-check"></i><b>3.7</b> Kruskal–Wallis Test</a></li>
<li class="chapter" data-level="3.8" data-path="multi-group-comparison-tests.html"><a href="multi-group-comparison-tests.html#pairwise.prop.test"><i class="fa fa-check"></i><b>3.8</b> pairwise.prop.test</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="applications.html"><a href="applications.html"><i class="fa fa-check"></i><b>4</b> Applications</a><ul>
<li class="chapter" data-level="4.1" data-path="applications.html"><a href="applications.html#example-one"><i class="fa fa-check"></i><b>4.1</b> Example one</a></li>
<li class="chapter" data-level="4.2" data-path="applications.html"><a href="applications.html#example-two"><i class="fa fa-check"></i><b>4.2</b> Example two</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>5</b> Final Words</a><ul>
<li class="chapter" data-level="5.1" data-path="final-words.html"><a href="final-words.html#pearson"><i class="fa fa-check"></i><b>5.1</b> Pearson</a></li>
<li class="chapter" data-level="5.2" data-path="final-words.html"><a href="final-words.html#chi-square"><i class="fa fa-check"></i><b>5.2</b> Chi-Square</a></li>
<li class="chapter" data-level="5.3" data-path="final-words.html"><a href="final-words.html#spearman"><i class="fa fa-check"></i><b>5.3</b> Spearman</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="final-words-1.html"><a href="final-words-1.html"><i class="fa fa-check"></i><b>6</b> Final Words</a><ul>
<li class="chapter" data-level="6.1" data-path="final-words-1.html"><a href="final-words-1.html#linear"><i class="fa fa-check"></i><b>6.1</b> Linear</a></li>
<li class="chapter" data-level="6.2" data-path="final-words-1.html"><a href="final-words-1.html#generalized-linear"><i class="fa fa-check"></i><b>6.2</b> Generalized Linear</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="Probablity.html"><a href="Probablity.html"><i class="fa fa-check"></i><b>7</b> Probability</a><ul>
<li class="chapter" data-level="7.1" data-path="Probablity.html"><a href="Probablity.html#bayesian-inference"><i class="fa fa-check"></i><b>7.1</b> Bayesian Inference</a></li>
<li class="chapter" data-level="7.2" data-path="Probablity.html"><a href="Probablity.html#stochastic-processes"><i class="fa fa-check"></i><b>7.2</b> Stochastic Processes</a><ul>
<li class="chapter" data-level="7.2.1" data-path="Probablity.html"><a href="Probablity.html#markov-chains"><i class="fa fa-check"></i><b>7.2.1</b> Markov Chains</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistics Handbook</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="two-group-comparison-tests" class="section level1">
<h1><span class="header-section-number">Chapter 2</span> Two-Group Comparison Tests</h1>
<p>Use <em>independent samples</em> tests to either <em>describe</em> a variable’s frequency or central tendency difference between two independent groups, or to <em>compare</em> the difference to a hypothesized value.</p>
<p>If the data generating process produces continuous outcomes (interval or ratio) and the outcomes are symmetrically distributed, the difference in the sample means, <span class="math inline">\(\hat{d} = \bar{x} - \bar{y}\)</span>, is a random variable centered at the population difference, <span class="math inline">\(d = \mu_X - \mu_Y\)</span>. You can use a theoretical distribution (normal or student t) to estimate a 95% confidence interval (CI) around <span class="math inline">\(d\)</span>, or compare <span class="math inline">\(\hat{d}\)</span> to an hypothesized population difference, <span class="math inline">\(d_0\)</span>. If you (somehow) know the sampling distribution variances <span class="math inline">\(\sigma^2_X\)</span> and <span class="math inline">\(\sigma^2_Y\)</span>, or the Central Limit Theorem (CLT) conditions hold, you can assume the random variable is normally distributed and use the <em>z</em>-test, otherwise assume the random variable has a student t distribution and use the <em>t</em>-test.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> If the data generating process produces continuous outcomes that are <em>not</em> symmetrically distributed, use a non-parametric test like the Mann-Whitney U test.</p>
<p>If the data generating process produces discrete outcomes (counts), the sample count, <span class="math inline">\(x\)</span>, is a random variable from a Poisson, binomial, normal, or multinomial distribution, or a random variable from a theoretical outcome. For two independent samples, the data can be organized into a two-way table - a frequency table for two categorical variables. If you have a single categorical predictor variable, you can test whether the joint frequency counts differ from the expected frequency counts in the saturated model. You analyze a two-way table one of two ways.</p>
<ul>
<li><p>If you only care about comparing two levels (like when the response variable is binary), conduct a proportion difference <em>z</em>-test or a Fisher exact test.</p></li>
<li><p>If you want to compare the joint frequency counts to <em>expected</em> frequency counts under the <em>independence model</em> (the model of independent explanatory variables), conduct a Pearson’s chi-squared independence test, or a <em>G</em>-test.</p></li>
</ul>
<div id="independent-samples-t-test" class="section level2">
<h2><span class="header-section-number">2.1</span> Independent Samples t Test</h2>
<p>If a population measure <em>X</em> is normally distributed with mean <span class="math inline">\(\mu_X\)</span> and variance <span class="math inline">\(\sigma_X^2\)</span>, and population measure <em>Y</em> is normally distributed with mean <span class="math inline">\(\mu_Y\)</span> and variance <span class="math inline">\(\sigma_Y^2\)</span>, then their difference is normally distributed with mean <span class="math inline">\(d = \mu_X - \mu_Y\)</span> and variance <span class="math inline">\(\sigma_{XY}^2 = \sigma_X^2 + \sigma_Y^2\)</span>. By the CLT, as the sample sizes grow, non-normally distributed <em>X</em> and <em>Y</em> will approach normality, and so will their difference.</p>
<p>The <strong>independent samples t-test</strong> uses the difference in sample means <span class="math inline">\(\hat{d} = \bar{x} - \bar{y}\)</span> as an estimate of <span class="math inline">\(d\)</span> to evaluate an hypothesized difference, <span class="math inline">\(d_0\)</span>. The null hypothesis is <span class="math inline">\(d = d_0\)</span>. Alternatively, you can construct a <span class="math inline">\((1 - \alpha)\%\)</span> confidence interval around <span class="math inline">\(\hat{d}\)</span> to estimate <span class="math inline">\(d\)</span> within a margin of error, <span class="math inline">\(\epsilon\)</span>.</p>
<p>In principal, you can test the difference between independent means with either a z test or a t test. Both require independent samples and approximately normal sampling distributions. The sampling distributions are normal if the underlying populations are normally distributed, or if the sample sizes are large (<span class="math inline">\(n_X\)</span> and <span class="math inline">\(n_Y\)</span> <span class="math inline">\(\ge\)</span> 30). However, the <em>z</em>-test additionally requires known sampling distribution variances <span class="math inline">\(\sigma^2_X\)</span> and <span class="math inline">\(\sigma^2_Y\)</span>. These variances are never known, so always use the <em>t</em>-test.</p>
<p>The <em>z</em>-test assumes <span class="math inline">\(d\)</span> has a normal distribution centered at <span class="math inline">\(\hat{d} = d\)</span> with standard error <span class="math inline">\(se = \sqrt{\frac{\sigma_X^2}{n_X} + \frac{\sigma_Y^2}{n_Y}}.\)</span> Test <span class="math inline">\(H_0: d = d_0\)</span> with test statistic <span class="math inline">\(Z = \frac{\hat{d} - d_0}{se}\)</span> or define a <span class="math inline">\((1 - \alpha)\%\)</span> confidence interval as <span class="math inline">\(d = \hat{d} \pm z_{(1 - \alpha {/} 2)} se\)</span>.</p>
<p>The <em>t</em>-test assumes <span class="math inline">\(d\)</span> has a <em>t</em> distribution centered at <span class="math inline">\(\hat{d} = d\)</span> with standard error <span class="math inline">\(se = \sqrt{\frac{s_X^2}{n_X} + \frac{s_Y^2}{n_Y}}.\)</span> Test <span class="math inline">\(H_0: d = d_0\)</span> with test statistic <span class="math inline">\(T = \frac{\hat{d} - d_0}{se}\)</span>, or define a <span class="math inline">\((1 - \alpha)\%\)</span> confidence interval as <span class="math inline">\(d = \hat{d} \pm t_{(1 - \alpha / 2), (n_X + n_Y - 2)} se\)</span>.</p>
<p>However, there is an issue with the <em>t</em> test degrees of freedom. If the sample sizes are small, and the standard deviations from each population are similar (the ratios of <span class="math inline">\(s_X\)</span> and <span class="math inline">\(s_Y\)</span> are &lt;2), you can pool the variances <span class="math inline">\(s_p^2 = \frac{(n_X - 1) s_X^2 + (n_Y-1) s_Y^2}{n_X + n_Y-2}\)</span> so that <span class="math inline">\(se = s_p \sqrt{\frac{1}{n_X} + \frac{1}{n_Y}}\)</span> and <span class="math inline">\(df = n_X + n_Y -2\)</span>. This is call the <strong>pooled variances t-test</strong>. Otherwise, <span class="math inline">\(se = \sqrt{\frac{s_X^2}{n_X} + \frac{s_Y^2}{n_Y}}\)</span>, but you must reduce the degrees of freedom using the Welch-Satterthwaite correction, <span class="math inline">\(df = \frac{\left(\frac{s_X^2}{n_X} + \frac{s_Y^2}{n_Y}\right)^2}{\frac{s_X^4}{n_X^2\left(N_X-1\right)} + \frac{s_Y^4}{n_Y^2\left(N_Y-1\right)}}.\)</span> This is called the <strong>separate variance t-test</strong>, or <strong>Welch’s t-test</strong>.</p>
<div id="example-5" class="section level4 unnumbered">
<h4>Example</h4>
<p>A company shows an advertisement to <span class="math inline">\(n_M\)</span> = 20 males and <span class="math inline">\(n_F\)</span> = 20 females, then measures their engagement with a survey. Do the mean engagement scores differ between the groups?</p>
<p><img src="statistics_files/figure-html/unnamed-chunk-3-1.png" width="624" /></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="two-group-comparison-tests.html#cb1-1"></a>engage_gt &lt;-<span class="st"> </span>engage <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb1-2"><a href="two-group-comparison-tests.html#cb1-2"></a><span class="st">  </span>gtsummary<span class="op">::</span><span class="kw">tbl_summary</span>(<span class="dt">by =</span> gender, </span>
<span id="cb1-3"><a href="two-group-comparison-tests.html#cb1-3"></a>                         <span class="dt">statistic =</span> <span class="kw">list</span>(<span class="kw">all_continuous</span>() <span class="op">~</span><span class="st"> &quot;{mean} ({sd})&quot;</span>))</span>
<span id="cb1-4"><a href="two-group-comparison-tests.html#cb1-4"></a>engage_gt</span></code></pre></div>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#gquqjaazhq .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#gquqjaazhq .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#gquqjaazhq .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#gquqjaazhq .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#gquqjaazhq .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#gquqjaazhq .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#gquqjaazhq .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#gquqjaazhq .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#gquqjaazhq .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#gquqjaazhq .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#gquqjaazhq .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#gquqjaazhq .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#gquqjaazhq .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#gquqjaazhq .gt_from_md > :first-child {
  margin-top: 0;
}

#gquqjaazhq .gt_from_md > :last-child {
  margin-bottom: 0;
}

#gquqjaazhq .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#gquqjaazhq .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#gquqjaazhq .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#gquqjaazhq .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#gquqjaazhq .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#gquqjaazhq .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#gquqjaazhq .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#gquqjaazhq .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#gquqjaazhq .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#gquqjaazhq .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#gquqjaazhq .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#gquqjaazhq .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#gquqjaazhq .gt_left {
  text-align: left;
}

#gquqjaazhq .gt_center {
  text-align: center;
}

#gquqjaazhq .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#gquqjaazhq .gt_font_normal {
  font-weight: normal;
}

#gquqjaazhq .gt_font_bold {
  font-weight: bold;
}

#gquqjaazhq .gt_font_italic {
  font-style: italic;
}

#gquqjaazhq .gt_super {
  font-size: 65%;
}

#gquqjaazhq .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="gquqjaazhq" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Male</strong>, N = 20<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Female</strong>, N = 20<sup class="gt_footnote_marks">1</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr>
      <td class="gt_row gt_left">engagement</td>
      <td class="gt_row gt_center">5.56 (0.29)</td>
      <td class="gt_row gt_center">5.30 (0.39)</td>
    </tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="3">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          Statistics presented: Mean (SD)
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table></div>
<p>You can report the following initially.</p>
<blockquote>
<p>There were 20 male and 20 female participants. Data are mean <span class="math inline">\(\pm\)</span> standard deviation, unless otherwise stated. The advertisement was more engaging to male viewers, 5.56 (0.29), than female viewers, 5.30 (0.39).</p>
</blockquote>
</div>
<div id="conditions-5" class="section level4 unnumbered">
<h4>Conditions</h4>
<p>The independent samples <em>t</em> test applies when the variable is continuous, partitioned into two independent samples, and the observations are independent. Additionally, there are three conditions related to the data distribution. If any condition fails, try the suggested work-around or use the non-parametric Mann-Whitney U Test instead.</p>
<ol style="list-style-type: decimal">
<li><strong>Outliers</strong>. There should be no outliers in either group because they exert a large influence on the mean and standard deviation. Test with a box plot. If there are outliers, you might be able to drop them or transform the data.</li>
<li><strong>Normality</strong>. Values should be <em>nearly</em> normally distributed (“nearly” because the <em>t</em>-test is robust to the normality assumption). This condition is especially important with small sample sizes. Test with Q-Q plots or the Shapiro-Wilk test for normality. If the data is very non-normal, you might be able to transform the data.</li>
<li><strong>Homogeneous Variances</strong>. If variances are homogenous, you can use the pooled-variances method; otherwise you use the separate variance method. Test with Levene’s test of equality of variances.</li>
</ol>
<div id="outliers-1" class="section level5 unnumbered">
<h5>Outliers</h5>
<p>Assess outliers with a box plot. Box plot whiskers extend up to 1.5*IQR from the upper and lower hinges and outliers (beyond the whiskers) are are plotted individually. There are no outliers is this plot. Report this as</p>
<blockquote>
<p>There were no outliers in the data, as assessed by inspection of a boxplot.</p>
</blockquote>
<p><img src="statistics_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>If the outliers are data entry errors or measurement errors, fix or discard them. If the outliers are genuine, you have a couple options before reverting to the Mann-Whitney U test.</p>
<ul>
<li>Leave it in if it doesn’t affect the conclusion (compared to taking it out).</li>
<li>Transform the variable. Don’t do this unless the variable is also non-normal. Transformation also has the downside of making interpretation more difficult.</li>
</ul>
</div>
<div id="normality-1" class="section level5 unnumbered">
<h5>Normality</h5>
<p>Assume the population is normally distributed if <em>n</em> <span class="math inline">\(\ge\)</span> 30. Otherwise, asses a Q-Q plot, skewness and kurtosis values, or a histogram. If you still don’t feel confident about normality, run a Mann-Whitney U Test.</p>
<p>The data set has <span class="math inline">\(n_M\)</span> = 20 male and <span class="math inline">\(n_F\)</span> = 20 female observations, so you need to test normality. The QQ plot indicates normality.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="two-group-comparison-tests.html#cb2-1"></a>engage <span class="op">%&gt;%</span></span>
<span id="cb2-2"><a href="two-group-comparison-tests.html#cb2-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">sample =</span> engagement, <span class="dt">group =</span> gender, <span class="dt">color =</span> <span class="kw">fct_rev</span>(gender))) <span class="op">+</span></span>
<span id="cb2-3"><a href="two-group-comparison-tests.html#cb2-3"></a><span class="st">  </span><span class="kw">stat_qq</span>() <span class="op">+</span></span>
<span id="cb2-4"><a href="two-group-comparison-tests.html#cb2-4"></a><span class="st">  </span><span class="kw">stat_qq_line</span>(<span class="dt">col =</span> <span class="st">&quot;goldenrod&quot;</span>) <span class="op">+</span></span>
<span id="cb2-5"><a href="two-group-comparison-tests.html#cb2-5"></a><span class="st">  </span><span class="kw">theme_minimal</span>() <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;top&quot;</span>) <span class="op">+</span></span>
<span id="cb2-6"><a href="two-group-comparison-tests.html#cb2-6"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Normal Q-Q Plot&quot;</span>, <span class="dt">color =</span> <span class="ot">NULL</span>)</span></code></pre></div>
<p><img src="statistics_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Both Shapiro-Wilk normality tests (males and females) fail to reject the normality assumption. Report this as</p>
<blockquote>
<p>Engagement scores for each level of gender were normally distributed, as assessed by Shapiro-Wilk’s test (p &gt; .05).</p>
</blockquote>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="two-group-comparison-tests.html#cb3-1"></a><span class="kw">split</span>(engage, engage<span class="op">$</span>gender) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb3-2"><a href="two-group-comparison-tests.html#cb3-2"></a><span class="st">  </span><span class="kw">map</span>(<span class="op">~</span><span class="kw">shapiro.test</span>(.<span class="op">$</span>engagement))</span></code></pre></div>
<pre><code>## $Male
## 
##  Shapiro-Wilk normality test
## 
## data:  .$engagement
## W = 0.98344, p-value = 0.9705
## 
## 
## $Female
## 
##  Shapiro-Wilk normality test
## 
## data:  .$engagement
## W = 0.96078, p-value = 0.5595</code></pre>
<p>If the data is not normally distributed, you still have a couple options before reverting to the Mann-Whitney U test.</p>
<ul>
<li>Transform the dependent variable.</li>
<li>Carry on regardless - the independent samples <em>t</em>-test is fairly robust to deviations from normality.</li>
</ul>
</div>
<div id="homogenous-variances" class="section level5 unnumbered">
<h5>Homogenous Variances</h5>
<p>Use the pooled-variances method if variances are homogeneous; otherwise use the separate variance method. A rule of thumb is that homogeneous variances have a ratio of standard deviations between 0.5 and 2.0:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="two-group-comparison-tests.html#cb5-1"></a><span class="kw">sd</span>(engage <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(gender <span class="op">==</span><span class="st"> &quot;Male&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(engagement)) <span class="op">/</span></span>
<span id="cb5-2"><a href="two-group-comparison-tests.html#cb5-2"></a><span class="st">  </span><span class="kw">sd</span>(engage <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(gender <span class="op">==</span><span class="st"> &quot;Female&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(engagement))</span></code></pre></div>
<pre><code>## [1] 0.7419967</code></pre>
<p>You can also use the <em>F</em> test to compare the ratio of the sample variances <span class="math inline">\(\hat{r} = s_X^2 / s_Y^2\)</span> to an hypothesized ratio of population variances <span class="math inline">\(r_0 = \sigma_X^2 / \sigma_Y^2 = 1.\)</span></p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="two-group-comparison-tests.html#cb7-1"></a><span class="kw">var.test</span>(engage <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(gender <span class="op">==</span><span class="st"> &quot;Female&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(engagement), </span>
<span id="cb7-2"><a href="two-group-comparison-tests.html#cb7-2"></a>         engage <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(gender <span class="op">==</span><span class="st"> &quot;Male&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(engagement))</span></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  engage %&gt;% filter(gender == &quot;Female&quot;) %&gt;% pull(engagement) and engage %&gt;% filter(gender == &quot;Male&quot;) %&gt;% pull(engagement)
## F = 1.8163, num df = 19, denom df = 19, p-value = 0.2025
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.7189277 4.5888826
## sample estimates:
## ratio of variances 
##           1.816336</code></pre>
<p>Bartlett’s test is a second option.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="two-group-comparison-tests.html#cb9-1"></a><span class="kw">bartlett.test</span>(engage<span class="op">$</span>engagement, engage<span class="op">$</span>gender)</span></code></pre></div>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  engage$engagement and engage$gender
## Bartlett&#39;s K-squared = 1.6246, df = 1, p-value = 0.2024</code></pre>
<p>Levene’s test is a third option. Levene’s is less sensitive to departures from normality than Bartlett.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="two-group-comparison-tests.html#cb11-1"></a>engage_report<span class="op">$</span>levene &lt;-<span class="st"> </span><span class="kw">with</span>(engage, car<span class="op">::</span><span class="kw">leveneTest</span>(engagement, gender, <span class="dt">center =</span> <span class="st">&quot;mean&quot;</span>))</span>
<span id="cb11-2"><a href="two-group-comparison-tests.html#cb11-2"></a>engage_report<span class="op">$</span>levene</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;mean&quot;)
##       Df F value Pr(&gt;F)
## group  1   1.922 0.1737
##       38</code></pre>
<p>Report these results as</p>
<blockquote>
<p>There was homogeneity of variances for engagement scores for males and females, as assessed by Levene’s test for equality of variances (<em>p</em> = 0.174).</p>
</blockquote>
</div>
</div>
<div id="results-5" class="section level4 unnumbered">
<h4>Results</h4>
<p>Conduct the <em>t</em>-test. To get a 95% CI around the <em>difference</em> (instead of around the estimate), run the test using the difference, <span class="math inline">\(\mu_0 - \bar{x}\)</span>, and leave <code>mu</code> at its default of 0.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="two-group-comparison-tests.html#cb13-1"></a>(engage_95ci &lt;-<span class="st"> </span><span class="kw">t.test</span>(engagement <span class="op">~</span><span class="st"> </span>gender, <span class="dt">data =</span> engage, <span class="dt">var.equal =</span> <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  engagement by gender
## t = 2.3645, df = 38, p-value = 0.02327
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.03725546 0.48074454
## sample estimates:
##   mean in group Male mean in group Female 
##             5.558875             5.299875</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="two-group-comparison-tests.html#cb15-1"></a>engage_gt</span></code></pre></div>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#mgkimlbiaj .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#mgkimlbiaj .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#mgkimlbiaj .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#mgkimlbiaj .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#mgkimlbiaj .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#mgkimlbiaj .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#mgkimlbiaj .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#mgkimlbiaj .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#mgkimlbiaj .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#mgkimlbiaj .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#mgkimlbiaj .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#mgkimlbiaj .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#mgkimlbiaj .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#mgkimlbiaj .gt_from_md > :first-child {
  margin-top: 0;
}

#mgkimlbiaj .gt_from_md > :last-child {
  margin-bottom: 0;
}

#mgkimlbiaj .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#mgkimlbiaj .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#mgkimlbiaj .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#mgkimlbiaj .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#mgkimlbiaj .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#mgkimlbiaj .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#mgkimlbiaj .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#mgkimlbiaj .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#mgkimlbiaj .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#mgkimlbiaj .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#mgkimlbiaj .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#mgkimlbiaj .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#mgkimlbiaj .gt_left {
  text-align: left;
}

#mgkimlbiaj .gt_center {
  text-align: center;
}

#mgkimlbiaj .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#mgkimlbiaj .gt_font_normal {
  font-weight: normal;
}

#mgkimlbiaj .gt_font_bold {
  font-weight: bold;
}

#mgkimlbiaj .gt_font_italic {
  font-style: italic;
}

#mgkimlbiaj .gt_super {
  font-size: 65%;
}

#mgkimlbiaj .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="mgkimlbiaj" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Male</strong>, N = 20<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Female</strong>, N = 20<sup class="gt_footnote_marks">1</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr>
      <td class="gt_row gt_left">engagement</td>
      <td class="gt_row gt_center">5.56 (0.29)</td>
      <td class="gt_row gt_center">5.30 (0.39)</td>
    </tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="3">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          Statistics presented: Mean (SD)
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table></div>
<p>Report this as:</p>
<blockquote>
<p>There was a statistically significant difference in mean engagement score between males and females, with males scoring higher than females, 0.26 (95% CI, 0.04 to 0.48), t(38) = 2.365, <em>p</em> = 0.023.</p>
</blockquote>
<p>The effect size, called Cohen’s <em>d</em>, is defined as <span class="math inline">\(d = |M_D| / s\)</span>, where <span class="math inline">\(|M_D| = \bar{x} - \bar{y}\)</span>, and <span class="math inline">\(s\)</span> is the pooled sample standard deviation, <span class="math inline">\(s_p = \sqrt{\frac{(n_X - 1) s_X^2 + (n_Y-1) s_Y^2}{n_X + n_Y-2}}\)</span>. <span class="math inline">\(d &lt;.2\)</span> is considered trivial, <span class="math inline">\(.2 \le d &lt; .5\)</span> small, and <span class="math inline">\(.5 \le d &lt; .8\)</span> large.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="two-group-comparison-tests.html#cb16-1"></a>(d &lt;-<span class="st"> </span>effectsize<span class="op">::</span><span class="kw">cohens_d</span>(engagement <span class="op">~</span><span class="st"> </span>gender, <span class="dt">data =</span> engage, <span class="dt">pooled_sd =</span> <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>## Cohen&#39;s d |       95% CI
## ------------------------
##      0.75 | [0.10, 1.39]
##  - Estimate using pooled SD</code></pre>
<p>Always construct a plot, just to make sure your head is on straight.</p>
<p><img src="statistics_files/figure-html/unnamed-chunk-15-1.png" width="720" /></p>
<p>Now you are ready to report the results.</p>
<blockquote>
<p>Data are mean <span class="math inline">\(\pm\)</span> standard deviation, unless otherwise stated. There were 20 male and 20 female participants. An independent-samples t-test was run to determine if there were differences in engagement to an advertisement between males and females. There were no outliers in the data, as assessed by inspection of a boxplot. Engagement scores for each level of gender were normally distributed, as assessed by Shapiro-Wilk’s test (<em>p</em> &gt; .05), and there was homogeneity of variances, as assessed by Levene’s test for equality of variances (<em>p</em> = 0.174). There were 20 male and 20 female participants. The advertisement was more engaging to male viewers (5.56 <span class="math inline">\(\pm\)</span> = 0.29) than female viewers (5.30 <span class="math inline">\(\pm\)</span> = 0.39), a statistically significant difference of 0.26 (95% CI, 0.04 to 0.48), t(38) = 2.365, <em>p</em> = 0.023, <em>d</em> = 0.75.</p>
</blockquote>
</div>
</div>
<div id="paired-samples-t-test" class="section level2">
<h2><span class="header-section-number">2.2</span> Paired Samples t Test</h2>
<p>The <em>paired two-sample test</em> uses the mean of sampled paired differences <span class="math inline">\(\bar{d} = \sum_{i = 1}^n (x_i - y_i) {/} n\)</span> as an estimate of the mean of the population paired differences <span class="math inline">\(\delta\)</span> to evaluate the hypothesized mean of population paired differences <span class="math inline">\(\delta_0\)</span>. Test <span class="math inline">\(H_0: \delta = \delta_0\)</span> with test statistic <span class="math inline">\(T = \frac{\bar{d} - \delta_0}{se}\)</span>, or define a <span class="math inline">\((1 - \alpha)\%\)</span> confidence interval as <span class="math inline">\(\delta = \bar{d} \pm t_{1 - \alpha / 2, n - 1} se\)</span>. <em>The paired t-test is really just a single mean t-test operating on variable that is defined as the difference between two variables</em>.</p>
<div id="example-6" class="section level4 unnumbered">
<h4>Example</h4>
<p><span class="math inline">\(n\)</span> = 20 athletes consume a carb-only or carb+protein drink prior to running as far as possible in 2 hours and a researcher measures their distances under both conditions. Does the mean differences in scores differ from 0?</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="two-group-comparison-tests.html#cb18-1"></a>drink_gt &lt;-<span class="st"> </span>drink <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb18-2"><a href="two-group-comparison-tests.html#cb18-2"></a><span class="st">  </span>gtsummary<span class="op">::</span><span class="kw">tbl_summary</span>(<span class="dt">statistic =</span> <span class="kw">list</span>(<span class="kw">all_continuous</span>() <span class="op">~</span><span class="st"> &quot;{mean} ({sd})&quot;</span>))</span>
<span id="cb18-3"><a href="two-group-comparison-tests.html#cb18-3"></a>drink_gt</span></code></pre></div>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#ykiicfvdyu .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ykiicfvdyu .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ykiicfvdyu .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ykiicfvdyu .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ykiicfvdyu .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ykiicfvdyu .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ykiicfvdyu .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ykiicfvdyu .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ykiicfvdyu .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ykiicfvdyu .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ykiicfvdyu .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ykiicfvdyu .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#ykiicfvdyu .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ykiicfvdyu .gt_from_md > :first-child {
  margin-top: 0;
}

#ykiicfvdyu .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ykiicfvdyu .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ykiicfvdyu .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#ykiicfvdyu .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ykiicfvdyu .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#ykiicfvdyu .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ykiicfvdyu .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ykiicfvdyu .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ykiicfvdyu .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ykiicfvdyu .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ykiicfvdyu .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#ykiicfvdyu .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ykiicfvdyu .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#ykiicfvdyu .gt_left {
  text-align: left;
}

#ykiicfvdyu .gt_center {
  text-align: center;
}

#ykiicfvdyu .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ykiicfvdyu .gt_font_normal {
  font-weight: normal;
}

#ykiicfvdyu .gt_font_bold {
  font-weight: bold;
}

#ykiicfvdyu .gt_font_italic {
  font-style: italic;
}

#ykiicfvdyu .gt_super {
  font-size: 65%;
}

#ykiicfvdyu .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="ykiicfvdyu" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>N = 20</strong><sup class="gt_footnote_marks">1</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr>
      <td class="gt_row gt_left">carb</td>
      <td class="gt_row gt_center">11.17 (0.73)</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">carb_protein</td>
      <td class="gt_row gt_center">11.30 (0.71)</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">difference</td>
      <td class="gt_row gt_center">0.14 (0.10)</td>
    </tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="2">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          Statistics presented: Mean (SD)
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table></div>
<p>You can report the following initially.</p>
<blockquote>
<p>There were 20 participants. Data are mean <span class="math inline">\(\pm\)</span> standard deviation, unless otherwise stated. Participants ran further after consuming the carbohydrate-protein drink, 11.30 (0.71) km, than the carbohydrate-only drink, 11.17 (0.73) km.</p>
</blockquote>
</div>
<div id="conditions-6" class="section level4 unnumbered">
<h4>Conditions</h4>
<p>The paired samples <em>t</em> test applies when the variable is continuous and a partitioned into dependent pairs, Additionally, there are two conditions related to the data distribution. If either condition fails, try the suggested work-around or use the non-parametric Wilcoxon Paired Sample Test instead.</p>
<ol style="list-style-type: decimal">
<li><strong>Outliers</strong>. There should be no outliers in differences because they exert a large influence on the mean and standard deviation. Test with a box plot. If there are outliers, you might be able to drop them or transform the data.</li>
<li><strong>Normality</strong>. Differences should be <em>nearly</em> normally distributed (“nearly” because the <em>t</em>-test is robust to the normality assumption). This condition is especially important with small sample sizes. Test with Q-Q plots or the Shapiro-Wilk test for normality. If the data is very non-normal, you might be able to transform the data.</li>
</ol>
<p>There are two common study designs that employ a paired samples t test to compare two related groups. One relates the groups as two time points for the same subjects. The second relates the groups as two tests of the same subjects, e.g. comparing reaction time under two lighting conditions.</p>
<div id="outliers-2" class="section level5 unnumbered">
<h5>Outliers</h5>
<p>Assess outliers with a box plot. Box plot whiskers extend up to 1.5*IQR from the upper and lower hinges and outliers (beyond the whiskers) are are plotted individually. The boxplot shows no outliers, although two points are actually right on the 1.5*IQR cusp.</p>
<p><img src="statistics_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Report inconsequential outliers as
&gt; Two outliers were detected that were more than 1.5 box-lengths from the edge of the box in a boxplot. Inspection of their values did not reveal them to be extreme and they were kept in the analysis.</p>
<p>or if there are no outliers, report as
&gt;There were no outliers in the data, as assessed by inspection of a boxplot.</p>
<p>If the outliers are data entry errors or measurement errors, fix them or discard them. If the outliers are genuine, you have a couple options before reverting to Wilcoxon.</p>
<ul>
<li>Transform the variable. Don’t do this unless the variable is also non-normal. Transformation also has the downside of making interpretation more difficult.</li>
<li>Leave it in if it doesn’t affect the conclusion (compared to taking it out).</li>
</ul>
</div>
<div id="normality-2" class="section level5 unnumbered">
<h5>Normality</h5>
<p>Assume the population is normally distributed if <em>n</em> <span class="math inline">\(\ge\)</span> 30. Otherwise, asses a Q-Q plot, skewness and kurtosis values, or a histogram. If you still don’t feel confident about normality, run a [Shapiro-Wilk Test].</p>
<p>The data set has <em>n</em> = 20 observations, so you cannot assume normality. The QQ plot indicates normality.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="two-group-comparison-tests.html#cb19-1"></a>drink <span class="op">%&gt;%</span></span>
<span id="cb19-2"><a href="two-group-comparison-tests.html#cb19-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">sample =</span> difference)) <span class="op">+</span></span>
<span id="cb19-3"><a href="two-group-comparison-tests.html#cb19-3"></a><span class="st">  </span><span class="kw">stat_qq</span>() <span class="op">+</span></span>
<span id="cb19-4"><a href="two-group-comparison-tests.html#cb19-4"></a><span class="st">  </span><span class="kw">stat_qq_line</span>(<span class="dt">col =</span> <span class="st">&quot;goldenrod&quot;</span>) <span class="op">+</span></span>
<span id="cb19-5"><a href="two-group-comparison-tests.html#cb19-5"></a><span class="st">  </span><span class="kw">theme_minimal</span>() <span class="op">+</span></span>
<span id="cb19-6"><a href="two-group-comparison-tests.html#cb19-6"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Normal Q-Q Plot&quot;</span>)</span></code></pre></div>
<p><img src="statistics_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>The Shapiro-Wilk normality test fails to reject the null hypothesis of a normally distributed population.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="two-group-comparison-tests.html#cb20-1"></a>drink_report<span class="op">$</span>shapiro &lt;-<span class="st"> </span><span class="kw">shapiro.test</span>(drink<span class="op">$</span>difference)</span>
<span id="cb20-2"><a href="two-group-comparison-tests.html#cb20-2"></a>drink_report<span class="op">$</span>shapiro</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  drink$difference
## W = 0.97119, p-value = 0.7797</code></pre>
<p>Report this as
&gt; The differences between the distance ran in the carbohydrate-only and carbohydrate-protein trial were normally distributed, as assessed by Shapiro-Wilk’s test (<em>p</em> = 0.780).</p>
<p>If the data is not normally distributed, you still have a couple options before reverting to Wilcoxon.</p>
<ul>
<li>Transform the dependent variable.</li>
<li>Carry on regardless - the one-sample <em>t</em>-test is fairly robust to deviations from normality.</li>
</ul>
</div>
</div>
<div id="results-6" class="section level4 unnumbered">
<h4>Results</h4>
<p>Conduct the <em>t</em>-test. To get a 95% CI around the <em>difference</em> (instead of around the estimate), run the test using the difference, <span class="math inline">\(\mu_0 - \bar{x}\)</span>, and leave <code>mu</code> at its default of 0.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="two-group-comparison-tests.html#cb22-1"></a>(drink_report<span class="op">$</span>ci &lt;-<span class="st"> </span><span class="kw">t.test</span>(</span>
<span id="cb22-2"><a href="two-group-comparison-tests.html#cb22-2"></a>  <span class="dt">x =</span> drink<span class="op">$</span>carb_protein, </span>
<span id="cb22-3"><a href="two-group-comparison-tests.html#cb22-3"></a>  <span class="dt">y =</span> drink<span class="op">$</span>carb, </span>
<span id="cb22-4"><a href="two-group-comparison-tests.html#cb22-4"></a>  <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, </span>
<span id="cb22-5"><a href="two-group-comparison-tests.html#cb22-5"></a>  <span class="dt">paired =</span> <span class="ot">TRUE</span>,</span>
<span id="cb22-6"><a href="two-group-comparison-tests.html#cb22-6"></a>  <span class="dt">conf.level =</span> <span class="fl">.95</span>)</span>
<span id="cb22-7"><a href="two-group-comparison-tests.html#cb22-7"></a>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  drink$carb_protein and drink$carb
## t = 6.3524, df = 19, p-value = 4.283e-06
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.09085492 0.18014508
## sample estimates:
## mean of the differences 
##                  0.1355</code></pre>
<p>Report this as:</p>
<blockquote>
<p>The carbohydrate-protein drink elicited an increase of 0.135 (95% CI, 0.091 to 0.180) km in the distance run in two hours compared to a carbohydrate-only drink.</p>
</blockquote>
<p>The effect size, called Cohen’s <em>d</em>, is defined as <span class="math inline">\(d = |M_D| / s\)</span>, where <span class="math inline">\(|M_D| = \bar{x} - \mu_0\)</span>, and <span class="math inline">\(s\)</span> is the sample standard deviation. <span class="math inline">\(d &lt;.2\)</span> is considered trivial, <span class="math inline">\(.2 \le d &lt; .5\)</span> small, and <span class="math inline">\(.5 \le d &lt; .8\)</span> large.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="two-group-comparison-tests.html#cb24-1"></a>(drink_report<span class="op">$</span>d &lt;-<span class="st"> </span>effectsize<span class="op">::</span><span class="kw">cohens_d</span>(drink<span class="op">$</span>difference))</span></code></pre></div>
<pre><code>## Cohen&#39;s d |       95% CI
## ------------------------
##      1.42 | [0.80, 2.09]
##  - Estimate using pooled SD</code></pre>
<p>Cohen’s <em>d</em> is 1.42, a large effect.</p>
<p>Construct a plot.</p>
<p><img src="statistics_files/figure-html/unnamed-chunk-23-1.png" width="624" /></p>
<p>Now you are ready to report the results.</p>
<blockquote>
<p>A paired-samples t-test was used to determine whether there was a statistically significant mean difference between the distance ran when participants drank a carbohydrate-protein drink compared to a carbohydrate-only drink. Data are mean <span class="math inline">\(\pm\)</span> standard deviation, unless otherwise stated. Two outliers were detected that were more than 1.5 box-lengths from the edge of the box in a boxplot. Inspection of their values did not reveal them to be extreme and they were kept in the analysis. The assumption of normality was not violated, as assessed by Shapiro-Wilk’s test (<em>p</em> = 0.780). Participants ran further after consuming the carbohydrate-protein drink, 11.30 (0.71) km, than the carbohydrate-only drink, 11.17 (0.73) km, a statistically significant increase of 0.135 (95% CI, 0.091 to 0.180) km, <em>t</em>(19) = 6.352, <em>p</em> = 0.0000, <em>d</em> = 1.42.</p>
</blockquote>
</div>
</div>
<div id="mann-whitney-u-test-for-numeric-vars" class="section level2">
<h2><span class="header-section-number">2.3</span> Mann-Whitney U Test for Numeric Vars</h2>
<p>This test applies when the variable distributions are non-normally.</p>
</div>
<div id="wilcoxon-paired-sample-test-for-numeric-vars" class="section level2">
<h2><span class="header-section-number">2.4</span> Wilcoxon Paired-Sample Test for Numeric Vars</h2>
<p>This test applies when the variable distributions are non-normally distributed and samples are paired.</p>
</div>
<div id="pearsons-correlation-for-numeric-vars" class="section level2">
<h2><span class="header-section-number">2.5</span> Pearson’s Correlation for Numeric Vars</h2>
</div>
<div id="spearmans-ranked-correlation-for-numeric-vars" class="section level2">
<h2><span class="header-section-number">2.6</span> Spearman’s Ranked Correlation for Numeric Vars</h2>
</div>
<div id="sample-independent-t-test-for-categorical-vars" class="section level2">
<h2><span class="header-section-number">2.7</span> 2 Sample Independent t Test for Categorical Vars</h2>
<p>This test applies when you know the population variance.</p>
</div>
<div id="sample-welchs-t-test-for-categorical-vars" class="section level2">
<h2><span class="header-section-number">2.8</span> 2 Sample Welch’s t Test for Categorical Vars</h2>
<p>This test applies when the variable variances are unequal.</p>
</div>
<div id="paired-sample-t-test-for-categorical-vars" class="section level2">
<h2><span class="header-section-number">2.9</span> Paired Sample t Test for Categorical Vars</h2>
<p>This test applies when you have paired samples.</p>
</div>
<div id="mann-whitney-u-test-for-categorical-vars" class="section level2">
<h2><span class="header-section-number">2.10</span> Mann-Whitney U Test for Categorical Vars</h2>
<p>This test applies when the variable distributions are non-normally.</p>
</div>
<div id="wilcoxon-paired-sample-test-for-categorical-vars" class="section level2">
<h2><span class="header-section-number">2.11</span> Wilcoxon Paired-Sample Test for Categorical Vars</h2>
<p>This test applies when the variable distributions are non-normally distributed and samples are paired.</p>
</div>
<div id="pearsons-correlation-for-categorical-vars" class="section level2">
<h2><span class="header-section-number">2.12</span> Pearson’s Correlation for Categorical Vars</h2>
</div>
<div id="spearmans-ranked-correlation-for-categorical-vars" class="section level2">
<h2><span class="header-section-number">2.13</span> Spearman’s Ranked Correlation for Categorical Vars</h2>
</div>
<div id="fishers-exact-test" class="section level2">
<h2><span class="header-section-number">2.14</span> Fisher’s Exact Test</h2>
<p>Use Fisher’s Exact Test to test whether the observed frequencies of a single discrete dichotomous variable are equal. Suppose you have a treatment and control, and a binary outcome with two levels, <em>sick</em> and <em>cured</em>. The</p>
<p>observed frequency counts, <span class="math inline">\(O_j\)</span>, of the <span class="math inline">\(J\)</span> levels of a categorical variable differ from the expected frequency counts, <span class="math inline">\(E_j\)</span>. <span class="math inline">\(H_0\)</span> is <span class="math inline">\(O_j = E_j\)</span>. The <em>p</em>-value from the test is computed as if the margins of the table are fixed. This leads under a null hypothesis of independence to a hypergeometric distribution of the numbers in the cells of the table</p>
<p>The test is applicable in situations where</p>
<ul>
<li>the row totals <span class="math inline">\(n_{i+}\)</span> and the column totals <span class="math inline">\(n_+j\)</span> are fixed by study design (rarely applies), and</li>
<li>the expected values of &gt;20% of cells (at least 1 cell in a 2x2 table) have expected cell counts &gt;5, and no expected cell count is &lt;1.</li>
</ul>
<p>In practice, it appears that researchers use Fisher’s exact test for 2x2 tables with small (<em>n</em> &lt; 1,000) sample sizes. It is more accurate than the chi-square and <em>G</em> tests.</p>
<p>([Wikipedial(<a href="https://en.wikipedia.org/wiki/Fisher%27s_exact_test" class="uri">https://en.wikipedia.org/wiki/Fisher%27s_exact_test</a>)). Fisher’s exact test is useful for small <em>n</em>-size samples where the chi-squared distribution assumption of the chi-squared and G-test tests fails. Fisher’s exact test is overly conservative (p values too high) for large <em>n</em>-sizes.</p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>The <em>t</em>-test returns nearly the same result as the <em>z</em>-test when the CLT holds, so in practice no one bothers with the <em>z</em>-test except as an aid to teach the <em>t</em>-test.<a href="two-group-comparison-tests.html#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="one-sample-inference-tests.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="multi-group-comparison-tests.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["statistics.pdf", "statistics.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
